# Generated by Django 4.0 on 2022-08-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_alter_iguser_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='ig_pk',
            field=models.PositiveIntegerField(blank=True, default=2, unique=True),
            preserve_default=False,
        ),
    ]
