# Generated by Django 4.0 on 2022-08-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_alter_location_ig_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='media_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='iguser',
            name='follower_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='iguser',
            name='following_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='iguser',
            name='media_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='ig_pk',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='like_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
