# Generated by Django 4.0 on 2022-08-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_alter_hashtag_media_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='ig_pk',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='ig_pk',
            field=models.CharField(blank=True, default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='ig_pk',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
